# Generated by Django 3.1.7 on 2021-04-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210414_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Content',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
